name: Docker Image CI

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Get version
        id: version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
      - name: Build the Docker image
        run: docker build --platform linux/amd64 -t rayenmabrouk/softyhr-server:linux-${{ steps.version.outputs.version }} .
